- hosts: all
  vars_files:
    - defaults/main.yml
  tasks:
    - include: tasks/main.yml
      vars:
        apt_install_packages:
          - wget
          - curl
          - vim
          - htop
          - net-tools
          - apt-transport-https
