---
# tasks file for linx-app-deploy

- name: Criar link para utilização do pacote Express pela aplicação
  shell: cd /tmp/linx/src && npm link express

- name: Criar link para utilização do pacote Express pela aplicação
  shell: cd /tmp/linx/src && npm link cluster

- name: Executando aplicação em background
  shell: cd /tmp/linx/src && nohup node app.js > /tmp/node_app_output.log
