---
- name: Verificando dependências
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Adicionar apt key para o NodeSource.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Adicionar repositório do NodeSource para Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Atualizar apt cache caso o repositório seja adicionado.
  apt: update_cache=yes
  when: node_repo.changed

- name: Garantir que nodejs e o npm estejam instalados.
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
